print("Hello World")
print('programming in python is interesting\n\nbarbie is fantastic animated movies to watch')
print()
print('how are you?\t create a beautiful place to live on earth by spreading love and care')
print('nothing in world is impossible you have to tey and focus to be on your way\t  be happy for healthy life')
print()
print('commitment is the best key to success in our life \ndo not let anyone put you down and get up whenever you are feeling low ')
print('fashion is most remarkable career for generation who aims to be creative  in the field of art')